### ISSUE TITLE
1.0.2 breaks back-compatibility

### ISSUE THREAD

**Issue by alexey-mercari** [googleapis/google-cloud-php-recaptcha-enterprise#2]
Following commit: https://github.com/googleapis/google-cloud-php-recaptcha-enterprise/commit/f933a0b5ecba7c4f6c143979df5986ac7310a4d8
renamed `scopes` to `defaultScopes`.

`defaultScopes` is a wrong name as it is ignored by google servers.

As a result, `scopes` now need to be explicitly set in the client configuration (which was not the case in v1.0.1).

---

Solution: rename `defaultScopes` to `scopes` back

**Comment by jdpedrie** [comment]
Let's continue the conversation here: https://github.com/googleapis/google-cloud-php/issues/3747
