### ISSUE TITLE
Adding a $response->getKey()

### ISSUE THREAD

**Issue by jamesmills** [googleapis/google-cloud-php-recaptcha-enterprise#7]
I notice there is a `$response->getName()` which returns the resource name for the Key in the format `"projects/{project}/keys/{key}"`. I think it would be nice to add a `$response->getKey()` to make it easier to just store the key locally.

Thanks

**Comment by jamesmills** [comment]
```
$key = 'projects/5678/keys/1234';
$str = substr($key, strpos($key, '/keys/') + strlen('/keys/'));

dd($str);

// 1234
```

**Comment by bshaffer** [comment]
This repository does not support issues. please file any issues at https://github.com/googleapis/google-cloud-php/issues
